app:
  name: Smart Classroom
  cleanup_on_exit: true

monitoring:
  logs_dir: ./monitoring/logs
  interval: 2
  socwatch_path: monitoring/tools/socwatch_windows_v2025.5.1/64/socwatch.exe
  npu_exe_path: tools/level-zero/build/bin/Release/npu_utilization.exe
  execution_logs: monitoring/executionlogs
models:
  asr:
    provider: openvino # openvino, funasr and openai supported
    name: whisper-tiny  # can be (whisper-base, whisper-small etc) or paraformer-zh
    device: CPU
    temperature: 0.0
    models_base_path: "models"
    threads_limit: Null # applied only if > 0 (else defaults are used); value can be tuned based on CPU specifications

  summarizer:
    provider: openvino # ipex or openvino
    name: Qwen/Qwen2-7B-Instruct # Qwen/Qwen1.5-7B-Chat, Qwen/Qwen2-7B-Instruct or Qwen/Qwen2.5-7B-Instruct
    device: GPU # GPU or CPU
    weight_format: int8 # supports fp16, fp32, int4, int8
    max_new_tokens: 1024
    temperature: 0.5 # 0.7 default
    use_cache: True
    models_base_path: "models"
    language: en # en or zh
    system_prompt: 
      en: "Summarize the classroom transcription concisely and in Markdown format with heading. Preserve the full meaning of the lecture, focusing on key points and concepts. Do not add commentary or extra details beyond the transcription."
      zh: "你是一个课堂教学助手，根据提供的原始课堂音频的转录文本，以Markdown格式提炼出本节课的核心内容、知识点结构、讲解顺序，解释每个知识点后，用简洁清晰的语言进行总结。注意不要遗漏主要知识点，也不要捏造任何没有提及的知识点，总结要保证知识点真实准确，避免任何冗余或误导性内容。"
    model_hub: huggingface # huggingface or modelscope

audio_preprocessing:
  chunk_duration_sec: 30
  silence_threshold: -35  # in dB
  silence_duration: 0.3   # minimum silence length in seconds
  search_window_sec: 1.5    # how far to look for silence if no silence exactly at chunk boundary
  chunk_output_path: chunks/

audio_util:
  max_size_mb: 200
  allowed_extensions:
    - .wav
    - .mp3
  chunk_size: 52428800   # 1024 * 1024 * 50 = 50MB

pipeline:
  delete_chunks_after_use: true
